[package]
name = "crdt-enc-password"
version = "0.1.0"
authors = ["Thomas Heck <t@b128.net>"]
edition = "2024"

[dependencies]
rand = { version = "0.10", features = ["thread_rng"] }
anyhow = "1"
serde = "1"
rmp-serde = "1"
serde_bytes = "0.11"
argon2 = "0.5"
zeroize = "1.9"
chacha20poly1305 = "0.11"
tokio = { version = "1", features = ["rt"] }
uuid = "1"

[dependencies.crdt-enc]
path = "../crdt-enc"

[dependencies.crdt-enc-envelope]
path = "../crdt-enc-envelope"

[dev-dependencies]
crdt-enc-tokio = { path = "../crdt-enc-tokio" }
crdts = "7"
tempfile = "3"
tokio = { version = "1", features = ["macros"] }
